### PR TITLE
@orta => Updates for CocoaPods 0.36 Beta 1

### LINKED ISSUE #1: Specify module name in podspec
Probably in a branch, since swift pods are still in beta. 

I'd assign this issue to myself, but I'm not listed as a collaborator on this repo cough cough.

### LINKED ISSUE #2: Fix frameworks issue
`fontWithName:` isn't working – there's already a PR that fixes this issue in our private fonts repo. I just need to reproduce it on this one after the PR is merged.

### PR DESCRIPTION
**Pull request by ashfurrow**
- Fixes #1. 
- Fixes #2.
- Adds CI. 

I can remove the Pods directory if you like.

### CODE REVIEW

**Comment by orta** [comment]
think it needs turning on on travis, 1 sec

**Comment by orta** [comment]
done, you could `--force` a push to trigger if you'd like

**Comment by ashfurrow** [comment]
Ah, sorry. I accidentally did a `git push -f` to Artsy's repo, not my fork. Will undo.

**Comment by ashfurrow** [comment]
:green_apple:

**Comment by ashfurrow** [comment]
Oh my gosh – having such a frustrating time with git tonight, sorry @orta.

**Comment by orta** [comment]
well it's green, so I think it's :ok:

**Pull request merged**
